spring.application.name=meeyazh-naturals-backend


# Supabase PostgreSQL Configuration
# DATABASE_URL: postgresql://postgres.[YOUR-PROJECT-REF]:[YOUR-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://db.ejpbbizfnexsrggstwht.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=QjOq6Z7BWSK4OPTA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=${PORT}
# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meeyazhnaturals@gmail.com
spring.mail.password=qwjrfsjjdhmhszcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
